#this setting Only use for mongodb-deployment.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_USERNAME: ENCRYPTED_USERNAME
  MONGO_PASSWORD: ENCRYPTED_PASSWORD
#for mongodb-statefulset1.yaml define user and password using mongo bash by execute "kubectl exec -it mongod-0 -- bash"
#                                                                                    kubectl exec -it <podName> -- bash
