apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
  namespace: uwauw
spec:
  serviceName: mongodb-service
  replicas: 3
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        replicaset: MainRepSet
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mongo-key
          secret:
            defaultMode: 0400
            secretName: mongo-key
      containers:
        - name: mongod-container
          image: radiantwf/mongodb-enterprise
          command:
            - 'mongod'
            - '--bind_ip'
            - '0.0.0.0'
            - '--replSet'
            - 'MainRepSet'
            - '--auth'
            - '--clusterAuthMode'
            - 'keyFile'
            - '--keyFile'
            - '/etc/secrets-volume/mongodb-keyfile'
            - '--setParameter'
            - 'authenticationMechanisms=SCRAM-SHA-1'
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-key
              mountPath: /etc/secrets-volume
              readOnly: true
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: 'role=mongo,environment=test'
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD
            - name: MONGODB_DATABASE
              value: admin
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: mongo-service
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage-claim
        annotations:
          volume.beta.kubernetes.io/storage-class: 'hostpath' #default storageclass
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi
